### ISSUE TITLE
Compare with drush-iq and drupalorg-cli

### ISSUE THREAD

**Issue by greg-1-anderson** [joachim-n/dorgflow#36]
https://www.drupal.org/project/drush_iq

Someone else has made a follow-on project for drush_iq as well, but I don't remember where it is now.

**Comment by greg-1-anderson** [comment]
Here it is:

https://github.com/mglaman/drupalorg-cli

**Comment by joachim-n** [comment]
Sorry for not responding sooner to this...

I'm aware of https://github.com/mglaman/drupalorg-cli, and there's also a script dawehner wrote that posts patches to d.org.

The three of us had a chat a while back, and while we're all in favour of joining forces, we also agreed that because drupal.org is moving to gitlab in the near future, we should wait and see what drupal.org issues will look like once that has happened.

**Comment by greg-1-anderson** [comment]
Just wanted to make sure you were aware. No action necessary.
